version: '3.9'
services:
  outsider:
    container_name: outsider-service
    image: 4n6e1/outsider-service:v1.0.3
    ports:
      - "60000:5126"
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
    depends_on:
      - eurekaserver
    links:
      - eurekaserver
  redis:
    container_name: redis-svc
    image: redis:alpine
    ports:
      - "60001:6379"
  eurekaserver:
    container_name: eureka-svc
    image: steeltoeoss/eureka-server
    ports:
      - "60003:8761"
  olc:
    container_name: olc-service
    image: 4n6e1/olcadapater-service:v1.0.3
    ports:
      - "60002:5103"
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
    depends_on:
      - outsider
      - redis
      - eurekaserver
    links:
      - outsider
      - redis
      - eurekaserver
