version: '3.9'
services:
  redis:
    container_name: redis-svc
    image: redis:alpine
    ports:
      - "60001:6379"
  eurekaserver:
    container_name: eureka-svc
    image: steeltoeoss/eureka-server
    ports:
      - "60003:8761"
  nip:
    container_name: nip-service
    image: 4n6e1/nip-service:v1
    ports:
      - "60001:5123"
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - REDISDATA_SVC_SERVICE_HOST=107.22.91.215
      - REDISDATA_SVC_SERVICE_PORT=60001
      - EUREKASERVER_SVC_SERVICE_HOST=107.22.91.215
      - EUREKASERVER_SVC_SERVICE_PORT=60003
    depends_on:
      - redis
      - eurekaserver
    links:
      - redis
      - eurekaserver
